// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package ports

import (
	"context"

	"github.com/Yusufdot101/ribble/services/user/internal/application/core/domain"
	mock "github.com/stretchr/testify/mock"
)

// NewMockAuthService creates a new instance of MockAuthService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockAuthService(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockAuthService {
	mock := &MockAuthService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockAuthService is an autogenerated mock type for the AuthService type
type MockAuthService struct {
	mock.Mock
}

type MockAuthService_Expecter struct {
	mock *mock.Mock
}

func (_m *MockAuthService) EXPECT() *MockAuthService_Expecter {
	return &MockAuthService_Expecter{mock: &_m.Mock}
}

// BeginAuth provides a mock function for the type MockAuthService
func (_mock *MockAuthService) BeginAuth() (string, string, string) {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for BeginAuth")
	}

	var r0 string
	var r1 string
	var r2 string
	if returnFunc, ok := ret.Get(0).(func() (string, string, string)); ok {
		return returnFunc()
	}
	if returnFunc, ok := ret.Get(0).(func() string); ok {
		r0 = returnFunc()
	} else {
		r0 = ret.Get(0).(string)
	}
	if returnFunc, ok := ret.Get(1).(func() string); ok {
		r1 = returnFunc()
	} else {
		r1 = ret.Get(1).(string)
	}
	if returnFunc, ok := ret.Get(2).(func() string); ok {
		r2 = returnFunc()
	} else {
		r2 = ret.Get(2).(string)
	}
	return r0, r1, r2
}

// MockAuthService_BeginAuth_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'BeginAuth'
type MockAuthService_BeginAuth_Call struct {
	*mock.Call
}

// BeginAuth is a helper method to define mock.On call
func (_e *MockAuthService_Expecter) BeginAuth() *MockAuthService_BeginAuth_Call {
	return &MockAuthService_BeginAuth_Call{Call: _e.mock.On("BeginAuth")}
}

func (_c *MockAuthService_BeginAuth_Call) Run(run func()) *MockAuthService_BeginAuth_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockAuthService_BeginAuth_Call) Return(authURL string, state string, nonce string) *MockAuthService_BeginAuth_Call {
	_c.Call.Return(authURL, state, nonce)
	return _c
}

func (_c *MockAuthService_BeginAuth_Call) RunAndReturn(run func() (string, string, string)) *MockAuthService_BeginAuth_Call {
	_c.Call.Return(run)
	return _c
}

// HandleCallback provides a mock function for the type MockAuthService
func (_mock *MockAuthService) HandleCallback(ctx context.Context, code string, nonce string) (string, string, error) {
	ret := _mock.Called(ctx, code, nonce)

	if len(ret) == 0 {
		panic("no return value specified for HandleCallback")
	}

	var r0 string
	var r1 string
	var r2 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string) (string, string, error)); ok {
		return returnFunc(ctx, code, nonce)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string) string); ok {
		r0 = returnFunc(ctx, code, nonce)
	} else {
		r0 = ret.Get(0).(string)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string, string) string); ok {
		r1 = returnFunc(ctx, code, nonce)
	} else {
		r1 = ret.Get(1).(string)
	}
	if returnFunc, ok := ret.Get(2).(func(context.Context, string, string) error); ok {
		r2 = returnFunc(ctx, code, nonce)
	} else {
		r2 = ret.Error(2)
	}
	return r0, r1, r2
}

// MockAuthService_HandleCallback_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'HandleCallback'
type MockAuthService_HandleCallback_Call struct {
	*mock.Call
}

// HandleCallback is a helper method to define mock.On call
//   - ctx context.Context
//   - code string
//   - nonce string
func (_e *MockAuthService_Expecter) HandleCallback(ctx interface{}, code interface{}, nonce interface{}) *MockAuthService_HandleCallback_Call {
	return &MockAuthService_HandleCallback_Call{Call: _e.mock.On("HandleCallback", ctx, code, nonce)}
}

func (_c *MockAuthService_HandleCallback_Call) Run(run func(ctx context.Context, code string, nonce string)) *MockAuthService_HandleCallback_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockAuthService_HandleCallback_Call) Return(refreshToken string, accessToken string, err error) *MockAuthService_HandleCallback_Call {
	_c.Call.Return(refreshToken, accessToken, err)
	return _c
}

func (_c *MockAuthService_HandleCallback_Call) RunAndReturn(run func(ctx context.Context, code string, nonce string) (string, string, error)) *MockAuthService_HandleCallback_Call {
	_c.Call.Return(run)
	return _c
}

// NewUser provides a mock function for the type MockAuthService
func (_mock *MockAuthService) NewUser(user *domain.User) error {
	ret := _mock.Called(user)

	if len(ret) == 0 {
		panic("no return value specified for NewUser")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(*domain.User) error); ok {
		r0 = returnFunc(user)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockAuthService_NewUser_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'NewUser'
type MockAuthService_NewUser_Call struct {
	*mock.Call
}

// NewUser is a helper method to define mock.On call
//   - user *domain.User
func (_e *MockAuthService_Expecter) NewUser(user interface{}) *MockAuthService_NewUser_Call {
	return &MockAuthService_NewUser_Call{Call: _e.mock.On("NewUser", user)}
}

func (_c *MockAuthService_NewUser_Call) Run(run func(user *domain.User)) *MockAuthService_NewUser_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 *domain.User
		if args[0] != nil {
			arg0 = args[0].(*domain.User)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockAuthService_NewUser_Call) Return(err error) *MockAuthService_NewUser_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockAuthService_NewUser_Call) RunAndReturn(run func(user *domain.User) error) *MockAuthService_NewUser_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockOAuthProvider creates a new instance of MockOAuthProvider. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockOAuthProvider(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockOAuthProvider {
	mock := &MockOAuthProvider{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockOAuthProvider is an autogenerated mock type for the OAuthProvider type
type MockOAuthProvider struct {
	mock.Mock
}

type MockOAuthProvider_Expecter struct {
	mock *mock.Mock
}

func (_m *MockOAuthProvider) EXPECT() *MockOAuthProvider_Expecter {
	return &MockOAuthProvider_Expecter{mock: &_m.Mock}
}

// GetAuthURL provides a mock function for the type MockOAuthProvider
func (_mock *MockOAuthProvider) GetAuthURL(state string, nonce string) string {
	ret := _mock.Called(state, nonce)

	if len(ret) == 0 {
		panic("no return value specified for GetAuthURL")
	}

	var r0 string
	if returnFunc, ok := ret.Get(0).(func(string, string) string); ok {
		r0 = returnFunc(state, nonce)
	} else {
		r0 = ret.Get(0).(string)
	}
	return r0
}

// MockOAuthProvider_GetAuthURL_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetAuthURL'
type MockOAuthProvider_GetAuthURL_Call struct {
	*mock.Call
}

// GetAuthURL is a helper method to define mock.On call
//   - state string
//   - nonce string
func (_e *MockOAuthProvider_Expecter) GetAuthURL(state interface{}, nonce interface{}) *MockOAuthProvider_GetAuthURL_Call {
	return &MockOAuthProvider_GetAuthURL_Call{Call: _e.mock.On("GetAuthURL", state, nonce)}
}

func (_c *MockOAuthProvider_GetAuthURL_Call) Run(run func(state string, nonce string)) *MockOAuthProvider_GetAuthURL_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockOAuthProvider_GetAuthURL_Call) Return(s string) *MockOAuthProvider_GetAuthURL_Call {
	_c.Call.Return(s)
	return _c
}

func (_c *MockOAuthProvider_GetAuthURL_Call) RunAndReturn(run func(state string, nonce string) string) *MockOAuthProvider_GetAuthURL_Call {
	_c.Call.Return(run)
	return _c
}

// GetUserInfo provides a mock function for the type MockOAuthProvider
func (_mock *MockOAuthProvider) GetUserInfo(ctx context.Context, code string, nonce string) (*domain.User, error) {
	ret := _mock.Called(ctx, code, nonce)

	if len(ret) == 0 {
		panic("no return value specified for GetUserInfo")
	}

	var r0 *domain.User
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string) (*domain.User, error)); ok {
		return returnFunc(ctx, code, nonce)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string) *domain.User); ok {
		r0 = returnFunc(ctx, code, nonce)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.User)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string, string) error); ok {
		r1 = returnFunc(ctx, code, nonce)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockOAuthProvider_GetUserInfo_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetUserInfo'
type MockOAuthProvider_GetUserInfo_Call struct {
	*mock.Call
}

// GetUserInfo is a helper method to define mock.On call
//   - ctx context.Context
//   - code string
//   - nonce string
func (_e *MockOAuthProvider_Expecter) GetUserInfo(ctx interface{}, code interface{}, nonce interface{}) *MockOAuthProvider_GetUserInfo_Call {
	return &MockOAuthProvider_GetUserInfo_Call{Call: _e.mock.On("GetUserInfo", ctx, code, nonce)}
}

func (_c *MockOAuthProvider_GetUserInfo_Call) Run(run func(ctx context.Context, code string, nonce string)) *MockOAuthProvider_GetUserInfo_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockOAuthProvider_GetUserInfo_Call) Return(user *domain.User, err error) *MockOAuthProvider_GetUserInfo_Call {
	_c.Call.Return(user, err)
	return _c
}

func (_c *MockOAuthProvider_GetUserInfo_Call) RunAndReturn(run func(ctx context.Context, code string, nonce string) (*domain.User, error)) *MockOAuthProvider_GetUserInfo_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockRepository creates a new instance of MockRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockRepository {
	mock := &MockRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockRepository is an autogenerated mock type for the Repository type
type MockRepository struct {
	mock.Mock
}

type MockRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *MockRepository) EXPECT() *MockRepository_Expecter {
	return &MockRepository_Expecter{mock: &_m.Mock}
}

// DeleteTokenByStringAndUse provides a mock function for the type MockRepository
func (_mock *MockRepository) DeleteTokenByStringAndUse(tokenString string, tokenUse domain.TokenUse) error {
	ret := _mock.Called(tokenString, tokenUse)

	if len(ret) == 0 {
		panic("no return value specified for DeleteTokenByStringAndUse")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(string, domain.TokenUse) error); ok {
		r0 = returnFunc(tokenString, tokenUse)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockRepository_DeleteTokenByStringAndUse_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DeleteTokenByStringAndUse'
type MockRepository_DeleteTokenByStringAndUse_Call struct {
	*mock.Call
}

// DeleteTokenByStringAndUse is a helper method to define mock.On call
//   - tokenString string
//   - tokenUse domain.TokenUse
func (_e *MockRepository_Expecter) DeleteTokenByStringAndUse(tokenString interface{}, tokenUse interface{}) *MockRepository_DeleteTokenByStringAndUse_Call {
	return &MockRepository_DeleteTokenByStringAndUse_Call{Call: _e.mock.On("DeleteTokenByStringAndUse", tokenString, tokenUse)}
}

func (_c *MockRepository_DeleteTokenByStringAndUse_Call) Run(run func(tokenString string, tokenUse domain.TokenUse)) *MockRepository_DeleteTokenByStringAndUse_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		var arg1 domain.TokenUse
		if args[1] != nil {
			arg1 = args[1].(domain.TokenUse)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockRepository_DeleteTokenByStringAndUse_Call) Return(err error) *MockRepository_DeleteTokenByStringAndUse_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockRepository_DeleteTokenByStringAndUse_Call) RunAndReturn(run func(tokenString string, tokenUse domain.TokenUse) error) *MockRepository_DeleteTokenByStringAndUse_Call {
	_c.Call.Return(run)
	return _c
}

// FindUserByProviderAndSub provides a mock function for the type MockRepository
func (_mock *MockRepository) FindUserByProviderAndSub(provider string, sub string) (*domain.User, error) {
	ret := _mock.Called(provider, sub)

	if len(ret) == 0 {
		panic("no return value specified for FindUserByProviderAndSub")
	}

	var r0 *domain.User
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(string, string) (*domain.User, error)); ok {
		return returnFunc(provider, sub)
	}
	if returnFunc, ok := ret.Get(0).(func(string, string) *domain.User); ok {
		r0 = returnFunc(provider, sub)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.User)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(string, string) error); ok {
		r1 = returnFunc(provider, sub)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockRepository_FindUserByProviderAndSub_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FindUserByProviderAndSub'
type MockRepository_FindUserByProviderAndSub_Call struct {
	*mock.Call
}

// FindUserByProviderAndSub is a helper method to define mock.On call
//   - provider string
//   - sub string
func (_e *MockRepository_Expecter) FindUserByProviderAndSub(provider interface{}, sub interface{}) *MockRepository_FindUserByProviderAndSub_Call {
	return &MockRepository_FindUserByProviderAndSub_Call{Call: _e.mock.On("FindUserByProviderAndSub", provider, sub)}
}

func (_c *MockRepository_FindUserByProviderAndSub_Call) Run(run func(provider string, sub string)) *MockRepository_FindUserByProviderAndSub_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockRepository_FindUserByProviderAndSub_Call) Return(user *domain.User, err error) *MockRepository_FindUserByProviderAndSub_Call {
	_c.Call.Return(user, err)
	return _c
}

func (_c *MockRepository_FindUserByProviderAndSub_Call) RunAndReturn(run func(provider string, sub string) (*domain.User, error)) *MockRepository_FindUserByProviderAndSub_Call {
	_c.Call.Return(run)
	return _c
}

// GetTokenByStringAndUse provides a mock function for the type MockRepository
func (_mock *MockRepository) GetTokenByStringAndUse(tokenString string, tokenUse domain.TokenUse) (*domain.Token, error) {
	ret := _mock.Called(tokenString, tokenUse)

	if len(ret) == 0 {
		panic("no return value specified for GetTokenByStringAndUse")
	}

	var r0 *domain.Token
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(string, domain.TokenUse) (*domain.Token, error)); ok {
		return returnFunc(tokenString, tokenUse)
	}
	if returnFunc, ok := ret.Get(0).(func(string, domain.TokenUse) *domain.Token); ok {
		r0 = returnFunc(tokenString, tokenUse)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.Token)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(string, domain.TokenUse) error); ok {
		r1 = returnFunc(tokenString, tokenUse)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockRepository_GetTokenByStringAndUse_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetTokenByStringAndUse'
type MockRepository_GetTokenByStringAndUse_Call struct {
	*mock.Call
}

// GetTokenByStringAndUse is a helper method to define mock.On call
//   - tokenString string
//   - tokenUse domain.TokenUse
func (_e *MockRepository_Expecter) GetTokenByStringAndUse(tokenString interface{}, tokenUse interface{}) *MockRepository_GetTokenByStringAndUse_Call {
	return &MockRepository_GetTokenByStringAndUse_Call{Call: _e.mock.On("GetTokenByStringAndUse", tokenString, tokenUse)}
}

func (_c *MockRepository_GetTokenByStringAndUse_Call) Run(run func(tokenString string, tokenUse domain.TokenUse)) *MockRepository_GetTokenByStringAndUse_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		var arg1 domain.TokenUse
		if args[1] != nil {
			arg1 = args[1].(domain.TokenUse)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockRepository_GetTokenByStringAndUse_Call) Return(token *domain.Token, err error) *MockRepository_GetTokenByStringAndUse_Call {
	_c.Call.Return(token, err)
	return _c
}

func (_c *MockRepository_GetTokenByStringAndUse_Call) RunAndReturn(run func(tokenString string, tokenUse domain.TokenUse) (*domain.Token, error)) *MockRepository_GetTokenByStringAndUse_Call {
	_c.Call.Return(run)
	return _c
}

// InsertToken provides a mock function for the type MockRepository
func (_mock *MockRepository) InsertToken(token *domain.Token) error {
	ret := _mock.Called(token)

	if len(ret) == 0 {
		panic("no return value specified for InsertToken")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(*domain.Token) error); ok {
		r0 = returnFunc(token)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockRepository_InsertToken_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'InsertToken'
type MockRepository_InsertToken_Call struct {
	*mock.Call
}

// InsertToken is a helper method to define mock.On call
//   - token *domain.Token
func (_e *MockRepository_Expecter) InsertToken(token interface{}) *MockRepository_InsertToken_Call {
	return &MockRepository_InsertToken_Call{Call: _e.mock.On("InsertToken", token)}
}

func (_c *MockRepository_InsertToken_Call) Run(run func(token *domain.Token)) *MockRepository_InsertToken_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 *domain.Token
		if args[0] != nil {
			arg0 = args[0].(*domain.Token)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockRepository_InsertToken_Call) Return(err error) *MockRepository_InsertToken_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockRepository_InsertToken_Call) RunAndReturn(run func(token *domain.Token) error) *MockRepository_InsertToken_Call {
	_c.Call.Return(run)
	return _c
}

// InsertUser provides a mock function for the type MockRepository
func (_mock *MockRepository) InsertUser(user *domain.User) error {
	ret := _mock.Called(user)

	if len(ret) == 0 {
		panic("no return value specified for InsertUser")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(*domain.User) error); ok {
		r0 = returnFunc(user)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockRepository_InsertUser_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'InsertUser'
type MockRepository_InsertUser_Call struct {
	*mock.Call
}

// InsertUser is a helper method to define mock.On call
//   - user *domain.User
func (_e *MockRepository_Expecter) InsertUser(user interface{}) *MockRepository_InsertUser_Call {
	return &MockRepository_InsertUser_Call{Call: _e.mock.On("InsertUser", user)}
}

func (_c *MockRepository_InsertUser_Call) Run(run func(user *domain.User)) *MockRepository_InsertUser_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 *domain.User
		if args[0] != nil {
			arg0 = args[0].(*domain.User)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockRepository_InsertUser_Call) Return(err error) *MockRepository_InsertUser_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockRepository_InsertUser_Call) RunAndReturn(run func(user *domain.User) error) *MockRepository_InsertUser_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockTokenService creates a new instance of MockTokenService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockTokenService(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockTokenService {
	mock := &MockTokenService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockTokenService is an autogenerated mock type for the TokenService type
type MockTokenService struct {
	mock.Mock
}

type MockTokenService_Expecter struct {
	mock *mock.Mock
}

func (_m *MockTokenService) EXPECT() *MockTokenService_Expecter {
	return &MockTokenService_Expecter{mock: &_m.Mock}
}

// DeleteTokenByStringAndUse provides a mock function for the type MockTokenService
func (_mock *MockTokenService) DeleteTokenByStringAndUse(tokenString string, tokenUse domain.TokenUse) error {
	ret := _mock.Called(tokenString, tokenUse)

	if len(ret) == 0 {
		panic("no return value specified for DeleteTokenByStringAndUse")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(string, domain.TokenUse) error); ok {
		r0 = returnFunc(tokenString, tokenUse)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockTokenService_DeleteTokenByStringAndUse_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DeleteTokenByStringAndUse'
type MockTokenService_DeleteTokenByStringAndUse_Call struct {
	*mock.Call
}

// DeleteTokenByStringAndUse is a helper method to define mock.On call
//   - tokenString string
//   - tokenUse domain.TokenUse
func (_e *MockTokenService_Expecter) DeleteTokenByStringAndUse(tokenString interface{}, tokenUse interface{}) *MockTokenService_DeleteTokenByStringAndUse_Call {
	return &MockTokenService_DeleteTokenByStringAndUse_Call{Call: _e.mock.On("DeleteTokenByStringAndUse", tokenString, tokenUse)}
}

func (_c *MockTokenService_DeleteTokenByStringAndUse_Call) Run(run func(tokenString string, tokenUse domain.TokenUse)) *MockTokenService_DeleteTokenByStringAndUse_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		var arg1 domain.TokenUse
		if args[1] != nil {
			arg1 = args[1].(domain.TokenUse)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockTokenService_DeleteTokenByStringAndUse_Call) Return(err error) *MockTokenService_DeleteTokenByStringAndUse_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockTokenService_DeleteTokenByStringAndUse_Call) RunAndReturn(run func(tokenString string, tokenUse domain.TokenUse) error) *MockTokenService_DeleteTokenByStringAndUse_Call {
	_c.Call.Return(run)
	return _c
}

// New provides a mock function for the type MockTokenService
func (_mock *MockTokenService) New(tokenType domain.TokenType, tokenUse domain.TokenUse, userID uint) (*domain.Token, error) {
	ret := _mock.Called(tokenType, tokenUse, userID)

	if len(ret) == 0 {
		panic("no return value specified for New")
	}

	var r0 *domain.Token
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(domain.TokenType, domain.TokenUse, uint) (*domain.Token, error)); ok {
		return returnFunc(tokenType, tokenUse, userID)
	}
	if returnFunc, ok := ret.Get(0).(func(domain.TokenType, domain.TokenUse, uint) *domain.Token); ok {
		r0 = returnFunc(tokenType, tokenUse, userID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.Token)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(domain.TokenType, domain.TokenUse, uint) error); ok {
		r1 = returnFunc(tokenType, tokenUse, userID)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockTokenService_New_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'New'
type MockTokenService_New_Call struct {
	*mock.Call
}

// New is a helper method to define mock.On call
//   - tokenType domain.TokenType
//   - tokenUse domain.TokenUse
//   - userID uint
func (_e *MockTokenService_Expecter) New(tokenType interface{}, tokenUse interface{}, userID interface{}) *MockTokenService_New_Call {
	return &MockTokenService_New_Call{Call: _e.mock.On("New", tokenType, tokenUse, userID)}
}

func (_c *MockTokenService_New_Call) Run(run func(tokenType domain.TokenType, tokenUse domain.TokenUse, userID uint)) *MockTokenService_New_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 domain.TokenType
		if args[0] != nil {
			arg0 = args[0].(domain.TokenType)
		}
		var arg1 domain.TokenUse
		if args[1] != nil {
			arg1 = args[1].(domain.TokenUse)
		}
		var arg2 uint
		if args[2] != nil {
			arg2 = args[2].(uint)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockTokenService_New_Call) Return(token *domain.Token, err error) *MockTokenService_New_Call {
	_c.Call.Return(token, err)
	return _c
}

func (_c *MockTokenService_New_Call) RunAndReturn(run func(tokenType domain.TokenType, tokenUse domain.TokenUse, userID uint) (*domain.Token, error)) *MockTokenService_New_Call {
	_c.Call.Return(run)
	return _c
}

// RefreshAccessToken provides a mock function for the type MockTokenService
func (_mock *MockTokenService) RefreshAccessToken(refreshTokenString string) (string, error) {
	ret := _mock.Called(refreshTokenString)

	if len(ret) == 0 {
		panic("no return value specified for RefreshAccessToken")
	}

	var r0 string
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(string) (string, error)); ok {
		return returnFunc(refreshTokenString)
	}
	if returnFunc, ok := ret.Get(0).(func(string) string); ok {
		r0 = returnFunc(refreshTokenString)
	} else {
		r0 = ret.Get(0).(string)
	}
	if returnFunc, ok := ret.Get(1).(func(string) error); ok {
		r1 = returnFunc(refreshTokenString)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockTokenService_RefreshAccessToken_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'RefreshAccessToken'
type MockTokenService_RefreshAccessToken_Call struct {
	*mock.Call
}

// RefreshAccessToken is a helper method to define mock.On call
//   - refreshTokenString string
func (_e *MockTokenService_Expecter) RefreshAccessToken(refreshTokenString interface{}) *MockTokenService_RefreshAccessToken_Call {
	return &MockTokenService_RefreshAccessToken_Call{Call: _e.mock.On("RefreshAccessToken", refreshTokenString)}
}

func (_c *MockTokenService_RefreshAccessToken_Call) Run(run func(refreshTokenString string)) *MockTokenService_RefreshAccessToken_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockTokenService_RefreshAccessToken_Call) Return(s string, err error) *MockTokenService_RefreshAccessToken_Call {
	_c.Call.Return(s, err)
	return _c
}

func (_c *MockTokenService_RefreshAccessToken_Call) RunAndReturn(run func(refreshTokenString string) (string, error)) *MockTokenService_RefreshAccessToken_Call {
	_c.Call.Return(run)
	return _c
}

// Save provides a mock function for the type MockTokenService
func (_mock *MockTokenService) Save(token *domain.Token) error {
	ret := _mock.Called(token)

	if len(ret) == 0 {
		panic("no return value specified for Save")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(*domain.Token) error); ok {
		r0 = returnFunc(token)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockTokenService_Save_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Save'
type MockTokenService_Save_Call struct {
	*mock.Call
}

// Save is a helper method to define mock.On call
//   - token *domain.Token
func (_e *MockTokenService_Expecter) Save(token interface{}) *MockTokenService_Save_Call {
	return &MockTokenService_Save_Call{Call: _e.mock.On("Save", token)}
}

func (_c *MockTokenService_Save_Call) Run(run func(token *domain.Token)) *MockTokenService_Save_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 *domain.Token
		if args[0] != nil {
			arg0 = args[0].(*domain.Token)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockTokenService_Save_Call) Return(err error) *MockTokenService_Save_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockTokenService_Save_Call) RunAndReturn(run func(token *domain.Token) error) *MockTokenService_Save_Call {
	_c.Call.Return(run)
	return _c
}

// getTokenByStringAndUse provides a mock function for the type MockTokenService
func (_mock *MockTokenService) getTokenByStringAndUse(tokenString string, tokenUse domain.TokenUse) (*domain.Token, error) {
	ret := _mock.Called(tokenString, tokenUse)

	if len(ret) == 0 {
		panic("no return value specified for getTokenByStringAndUse")
	}

	var r0 *domain.Token
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(string, domain.TokenUse) (*domain.Token, error)); ok {
		return returnFunc(tokenString, tokenUse)
	}
	if returnFunc, ok := ret.Get(0).(func(string, domain.TokenUse) *domain.Token); ok {
		r0 = returnFunc(tokenString, tokenUse)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.Token)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(string, domain.TokenUse) error); ok {
		r1 = returnFunc(tokenString, tokenUse)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockTokenService_getTokenByStringAndUse_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'getTokenByStringAndUse'
type MockTokenService_getTokenByStringAndUse_Call struct {
	*mock.Call
}

// getTokenByStringAndUse is a helper method to define mock.On call
//   - tokenString string
//   - tokenUse domain.TokenUse
func (_e *MockTokenService_Expecter) getTokenByStringAndUse(tokenString interface{}, tokenUse interface{}) *MockTokenService_getTokenByStringAndUse_Call {
	return &MockTokenService_getTokenByStringAndUse_Call{Call: _e.mock.On("getTokenByStringAndUse", tokenString, tokenUse)}
}

func (_c *MockTokenService_getTokenByStringAndUse_Call) Run(run func(tokenString string, tokenUse domain.TokenUse)) *MockTokenService_getTokenByStringAndUse_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		var arg1 domain.TokenUse
		if args[1] != nil {
			arg1 = args[1].(domain.TokenUse)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockTokenService_getTokenByStringAndUse_Call) Return(token *domain.Token, err error) *MockTokenService_getTokenByStringAndUse_Call {
	_c.Call.Return(token, err)
	return _c
}

func (_c *MockTokenService_getTokenByStringAndUse_Call) RunAndReturn(run func(tokenString string, tokenUse domain.TokenUse) (*domain.Token, error)) *MockTokenService_getTokenByStringAndUse_Call {
	_c.Call.Return(run)
	return _c
}
